plugins {
    id 'java'
    id 'application'
    id "io.github.0ffz.github-packages" version "1.2.1"
}

group = 'com.mtsharpgrain'
version = '0.1.0-beta2'

application {
    applicationName = 'MtSharpGrain'
    mainClass = 'com.mtsharpgrain.Main'
    applicationDefaultJvmArgs = ['-XstartOnFirstThread']
}

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
    flatDir {
        dirs 'libs'
    }
}

project.ext {
    jmeVer = '3.9.0-stable'
}

project(":assets") {
    apply plugin: "java"

    layout.buildDirectory.set(rootProject.file("build/assets"))

    sourceSets {
        main {
            resources {
                srcDir '.'
            }
        }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}

dependencies {
    // Core JME
    implementation "org.jmonkeyengine:jme3-core:$jmeVer"
    implementation "org.jmonkeyengine:jme3-desktop:$jmeVer"

    if (!System.getProperty("os.name").toLowerCase().contains("mac")) {
        implementation "org.jmonkeyengine:jme3-awt-dialogs:$jmeVer"
    }
    implementation "org.jmonkeyengine:jme3-lwjgl3:$jmeVer"

    implementation "org.jmonkeyengine:jme3-jogg:$jmeVer"
    implementation "org.jmonkeyengine:jme3-plugins:$jmeVer"
    implementation "org.jmonkeyengine:jme3-jbullet:$jmeVer"
    implementation "org.jmonkeyengine:jme3-networking:$jmeVer"
    implementation "org.jmonkeyengine:jme3-effects:$jmeVer"
    implementation "org.jmonkeyengine:jme3-terrain:$jmeVer"
    implementation "org.jmonkeyengine:jme3-testdata:$jmeVer"
    implementation "com.epagagames:particlemonkey:1.1.0"
    implementation "com.github.polincdev:ShaderBlowEx:-SNAPSHOT"

    implementation "com.github.stephengold:Heart:9.2.0"
    implementation "com.github.stephengold:SkyControl:1.1.0"

    implementation "org.graalvm.polyglot:polyglot:24.1.1"
    implementation "org.graalvm.polyglot:js-community:24.1.1"
    
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    runtimeOnly project(':assets')
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

wrapper {
    gradleVersion = '8.6'
}

tasks.withType(JavaExec).configureEach {
    jvmArgs += ['-XstartOnFirstThread']
}
